#!/bin/bash
# Jupyter specific additions
jupyter serverextension enable --py nbgitpuller --sys-prefix
# JKernel postBuild file to setup a JKernel on Binder
# get a J runtime
wget http://www.jsoftware.com/download/j903/install/j903_linux64.tar.gz 
tar -xf j903_linux64.tar.gz 
rm -rf j903_linux64.tar.gz
# export J_INSTALLATION_FOLDER="${HOME}/J903"
# export J_BIN_FOLDER="${HOME}/J903/bin"

# get J libraries
${HOME}/getjlibs.sh
git clone https://github.com/martin-saurer/jkernel
# echo ${HOME}
python ${HOME}/jkernel/setup.py install
